[package]
name = "rust-learn"
version = "0.1.0"
authors = ["chandanmadhesia"]
edition = "2018"

[[bin]]
name = "hello_world"
path = "src/leetcode/hello_world/main.rs"

[[bin]]
name = "rotate_image"
path = "src/leetcode/rotate_image/main.rs"

[dependencies]
